Repository microcks/microcks.io, pull requests merged in 2025-02, with the labels that each got.

#331 fixed place holder of search box visible clear with dark mode
  themes/microcks/assets/scss/templates/_search-modal.scss
Labels: component/ux, kind/enhancement, component/documention

#332 Change microcks-anywhere.png image for dark mode
  assets/images/microcks-anywhere.png
Labels: component/ux, kind/enhancement

#338 Fix 20: Fixed Active Dropdown Menu Logic
  themes/microcks/assets/scss/templates/_navigation.scss
  themes/microcks/layouts/partials/header.html
Labels: kind/bug, component/ux, kind/enhancement

#344 cache is shared across runs on the same branch
  .github/workflows/external-link-check.yml
Labels: kind/bug, kind/enhancement, automated issue

#347 improve the hugo server building in CI
  .github/workflows/hugo-build-status-check.yml
Labels: kind/bug, kind/enhancement, automated issue

#340 fixed yml syntax in external-link file
  .github/workflows/external-link-check.yml
Labels: kind/bug, contribution message

#357 fix: update 'Platform Engineer' icon color
  .gitignore
  assets/images/documentation/platform-engineer.png
Labels: kind/enhancement, component/documentation

#360 fixed the logic for issue creation
  .github/workflows/external-link-check.yml
Labels: kind/bug, kind/enhancement, automated issue, contribution message
